version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    auth:
       username: santhosh270
       password: Catalyst@test123
jobs:
  Deployment:
    runner: Machine
    image: image
    steps:
      - ls
      - pwd
      - npm i -g zcatalyst-cli@latest
      - catalyst --version
      - cd functions/pipeline_function
      - npm install --platform=linux --arch=x64
      - cd ../..
      - echo `catalyst deploy --project 27833000000008058 --org 862569740 --only functions --token m_1004.af2a065472259ebceabb987ff97f77f7.5da80c8b3eecc12b25b41b95c3d9d5ef`
      - catalyst deploy --project 27833000000008058 --org 862569740 --only functions --token m_1004.af2a065472259ebceabb987ff97f77f7.5da80c8b3eecc12b25b41b95c3d9d5ef

  AppsailDeployment:
    runner: Machine
    image: image
    steps:
      - ls
      - pwd
      - npm i -g zcatalyst-cli@latest
      - catalyst --version
      - catalyst deploy --project 27833000000008058 --org 862569740 --only appsail --token m_1004.b567de6517c815989b488a4fb29b756d.da26fbfc659500fe2041b496c932e8d8
stages:
  - name: Deployment
    jobs:
      - Deployment
      - AppsailDeployment