version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    auth:
       username: santhosh270
       password: Catalyst@test123
jobs:
  Deployment:
    runner: Machine
    image: image
    steps:
      - ls
      - pwd
      - npm i -g zcatalyst-cli@beta
      - catalyst --version
      - catalyst deploy --project 27833000000008058 --org 862569740 --token m_1004.f7c1029d8034ad5a819592479ee58de7.41199573461f2037ea672999cc82e0e8
stages:
  - name: Deployment
    jobs:
      - Deployment